### PR TITLE
New textures and added UFORace-like nodes

### PR DESCRIPTION
**Pull request by kaadmy**
I've added images that look more like Kenney's original images, and tried to fix the creative mode a bit.

### CODE REVIEW

**Comment by CasimirKaPazi** [comment]
It crashes when on_use is called. "games/uforun/mods/creative/init.lua:13: attempt to call method 'getpos' (a nil value)"
Pointing at a node is still required btw. I made an issue on this last year [#1548](https://github.com/minetest/minetest/issues/1548).

Other than that it is good to merge I think. The textures look good, and I will use the ufo as the 2D player sprite as soon as I figured out if it is possible to make the player smaller.

**Comment by cdqwertz** [comment]
I think you do not need uforun_dirt.png, uforun_ice.png... I already did that with one texture, we just need these special textures (dirt_grass, coin) :)

**Comment by kaadmy** [comment]
All right then, I just put those textures in because I already made them, you can leave them out or not use them as you wish.

**Comment by CasimirKaPazi** [comment]
We can still unify this afterwards. At the moment all is just about getting the basic functionality to work.

**Comment by cdqwertz** [comment]
ok

**Pull request merged**
