### PR TITLE
Update UFO model to ufo.obj and change code

### PR DESCRIPTION
**Pull request by benrob0329**
New texture/mapping allows for greater customization of one's own UFO.

Moved duplicate player model declaration in player.lua to ufo/init.lua (rather than it doing it on its own)

Changed model to ufo.obj so that it can be imported into Blender.

### CODE REVIEW

**Comment by wilkgr76** [comment]
:+1:

**Comment by cdqwertz** [comment]
Looks good :+1: 

The license is still missing...

**Comment by benrob0329** [comment]
Added

**Comment by wilkgr76** [comment]
Why does it have conflicts now?

**Comment by benrob0329** [comment]
The license file was changed, fixing now..

**Comment by benrob0329** [comment]
That was WAY more complicated than it needed to be....

Oh well, all in the process of learning Git I guess....

**Comment by benrob0329** [comment]
I'm going to see if I cant squash some of these commits.

**Comment by benrob0329** [comment]
Never mind, too much happened and I cant get it to squash.

**Comment by wilkgr76** [comment]
@benrob0329 Whatever. Have some lemon squash instead. Then again, have some :ice_cream: .

**(mouth full)**

"It's delicious!"

**Comment by cdqwertz** [comment]
great! :+1:

**Comment by wilkgr76** [comment]
@benrob0329 @cdqwertz Updated my joke, added squash pun (because @benrob0329 was trying to squash the commits, and squash is also a drink...)

**Comment by benrob0329** [comment]
XD

**Comment by wilkgr76** [comment]
@benrob0329 Comedian is back in service :clap:

**Comment by cdqwertz** [comment]
xD

**Comment by wilkgr76** [comment]
@cdqwertz @benrob0329 I have found my true occupation at last...

**Pull request merged**
