### PR TITLE
created more of the code structure (nodes.lua...)

### PR DESCRIPTION
**Pull request by cdqwertz**
I will add more content soon, but I am still working on some things :)

### CODE REVIEW

**Comment by CasimirKaPazi** [comment]
One will probably build the levels by hand floating in air. So we would not need a mapgen and no mapgen.lua, but mg_name = singlenode in the settings.
If you remove the mapgen.lua then this is good to merge.

**Comment by cdqwertz** [comment]
Casimir : we need it to build a basic floating island (level start)

**Comment by CasimirKaPazi** [comment]
Hm, ok.

**Comment by cdqwertz** [comment]
thank you :D

**Pull request merged**
