### PR TITLE
Add UFO model and remove old code/textures

### PR DESCRIPTION
**Pull request by benrob0329**
Added ufo.b3d model.

Removed UFO mod and unused textures.

Added code in mods/uforun/player.lua for new model.

Removed spawner code from mods/levelnodes/nodes.lua

### CODE REVIEW

**Comment by cdqwertz** [comment]
could you rebase this?
You removed lots of code we still need...

**Comment by benrob0329** [comment]
Which code?

**Comment by benrob0329** [comment]
Nvm, I see.

**Comment by benrob0329** [comment]
Are the most recent changes commited or did I do something wrong?

**Comment by cdqwertz** [comment]
nothing changed... I think we should close this pull and open a new one - thats the easiest way

**Comment by benrob0329** [comment]
K, but what needs to change?

**Comment by cdqwertz** [comment]
Fork the newest version of UfoRun and add the ufo model again (just copy the model file from the current pull).

**Comment by benrob0329** [comment]
Do you need the ufo mod?

**Comment by cdqwertz** [comment]
what do you mean?

**Comment by benrob0329** [comment]
I mean since it wont be used, can I remove it in the pull?

**Comment by cdqwertz** [comment]
we still need it :)

**Comment by benrob0329** [comment]
Can I remove the spawner code from nodes.lua?

**Comment by cdqwertz** [comment]
yea

**Comment by benrob0329** [comment]
#19

**Pull request closed without merging**
