### PR TITLE
Add hotbar textures.

### PR DESCRIPTION
**Pull request by wilkgr76**
I don't really need to say anything else, right?

### CODE REVIEW

**Comment by cdqwertz** [comment]
looks good :+1: 
But add a license for these images (License.txt) please :)

**Comment by wilkgr76** [comment]
Ok, will do :smile:

**Comment by wilkgr76** [comment]
@cdqwertz The system is so complex...Please merge first... I can't make sense on how to add another pull request :angry:

**Comment by benrob0329** [comment]
Commit the change to your fork, the changes will reflect here.

**Comment by cdqwertz** [comment]
I think GPL is for code, not for images...
There already is a LICENSE.txt in the folder uforun/mods/LICENSE.txt
Please add your license there

PS : I know that git is very complicated, I also dont understand it very well

**Comment by wilkgr76** [comment]
@cdqwertz Oh. :dizzy_face:

**Comment by wilkgr76** [comment]
Why did I close this? I don't know. Reopening :smile:

**Comment by wilkgr76** [comment]
Why did I close this? I don't know. Reopening :smile:

**Pull request closed without merging**
