### PR TITLE
added some things

### PR DESCRIPTION
**Pull request by cdqwertz**
I added
- mapgen singlenode
- some nodes, I think that I will add more soon :)
- jump 2 blocks (It worked with gravity = 1.0 (normaly 0.5 - I think) pls try it out and change it after merging)

### CODE REVIEW

**Comment by CasimirKaPazi** [comment]
I like the way you make nodes. This should definitely be add.

In general it is good to split pull requests up into separate chunks, one per feature. And describe what you did in the commit message. This way one does not have to read the code to know what is changed. You can use branches for this, with them you can have multiple pull request at the same time.

It seems you also included the backup files that where automatically created. It would be nice to remove them from the pr. I added a gitignore to prevent accidentally adding them in the future.

Your changes to init and mapgen are good. I wonder why mg_name in minetest.conf does not work. But your method does.
About nodes; As said, I really like them. But I would not use the crumbly group but maybe oddly_breakable_by_hand or dig_immediate.
About player.lua; Setting the gravity per player is not needed, we can just use movement_gravity in minetest.conf

**Comment by cdqwertz** [comment]
I dont like the minetest.conf way, bc I think that not every server admin will do that or, he/she will edit it randomly (I will do that XD) so its better to set the gravity in the code.

**Comment by CasimirKaPazi** [comment]
The minetest.conf in subgames gets used automatically. And it should not be edited by server admins. Instead they can use their local minetest.conf which then overrides the subgame settings.
Having gravity in the config allows users to use a custom gravity just the way they are used from other subgames. It's a convenient standard.

**Comment by CasimirKaPazi** [comment]
I just looked up the physics_override function you use for gravity. The default value is 1 and it just modifies the gravity set in the settings for the player. So server owners can still set their gravity to a different value if they want. Having the value in the code does not make is more robust.

It would be best if you just add your init.lua, nodes.lua add mapgen.lua as individual commits. We can then build upon this and discuss the rest separately.

**Comment by cdqwertz** [comment]
I merged this now, and I am going to remove the gravity things

**Pull request merged**
